services:
  pingpong-api:
    build: .
    container_name: pingpong-api
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./public:/app/public
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - webnet

networks:
  webnet:
    external: true
    name: docker_webnet
